### ISSUE TITLE
Master failing to build 

### ISSUE THREAD

**Issue by madhurranjan** [googledatalab/datalab#1513] opened 2017-07-18 23:37 UTC
Hi,

build.sh on master is failing with the following error.
`
Building web ...
../../../../../node_modules/@types/request/index.d.ts(66,15): error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>; (options: (UriOptions & TO...'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'delete' are incompatible.
          Type '{ (uri: string, options?: TOptions | undefined, callback?: request.RequestCallback | undefined): ...' is not assignable to type '{ (uri: string, options?: TOptions | undefined, callback?: request.RequestCallback | undefined): ...'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'options' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'OptionalUriUrl & TOptions'.
                Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl & TOptions'.
                  Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl'.
                    Types of property 'uri' are incompatible.
                      Type 'string | Url' is not assignable to type 'string | undefined'.
                        Type 'Url' is not assignable to type 'string | undefined'.
                          Type 'Url' is not assignable to type 'string'.
failed
Build aborted.`

**Comment by yebrahim** [comment] 2017-07-22 01:09
This doesn't look like a Datalab error to me.
Is this a fresh clone of Datalab? What version of typescript are you using? (do `tsc --version`)

**Comment by chmeyers** [comment] 2017-08-15 20:05
Since we don't seem to have a repro for this, I'm closing.  Feel free to reopen if you know what the issue is.

**Closed by chmeyers** 2017-08-15 20:05 UTC
