### ISSUE TITLE
problems reconnecting to datalab (ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].)

### ISSUE THREAD

**Issue by brilindquist** [googledatalab/datalab#2026] opened 2018-06-28 15:54 UTC
Hi,
  I periodically have problems trying to re-connect to a datalab instance. 

Running from the Google Cloud Shell, I type:

> datalab  connect brilindquist-test-3

I get the following error message:

> Waiting for Datalab to be reachable at http://localhost:8081/
> Permission denied (publickey).
> ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
> Connection broken
> Attempting to reconnect...

My gcloud version:

> Google Cloud SDK 207.0.0
> alpha 2018.06.22
> app-engine-go
> app-engine-java 1.9.64
> app-engine-php " "
> app-engine-python 1.9.71
> app-engine-python-extras 1.9.69
> beta 2018.06.22
> bq 2.0.34
> cbt
> cloud-datastore-emulator 2.0.0
> container-builder-local
> core 2018.06.22
> datalab 20180503
> docker-credential-gcr
> gcd-emulator v1beta3-1.0.0
> gsutil 4.32
> kubectl
> pubsub-emulator 2018.02.02

I tried to ssh to the VM instance from the Cloud Console (Compute Engine --> VM Instances --> SSH --> Open in browser window), but this didn't work: I waited for 10 minutes for it to connect, without success, and finally I cancelled the connection.

I also couldn't ssh from the Cloud Shell (gcloud compute ssh datalab@brilindquist-test-3). I got
the error message:

> Permission denied (publickey).
> ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].

In this case, doing "datalab stop" and "datalab connect" a couple of times eventually fixed the problem, but this is a recurring issue.

**Comment by ojarjur** [comment] 2018-06-28 22:21
@brilindquist Since it is sporadic and blocks *all* ssh access, the next step should be for us to try to get some additional logs of what is going one.

The next time this happens, try running the `datalab connect` command with an addition flag of `--ssh-log-level=debug`.

That will give us more logging on what is happening on the client side.

That probably won't be enough, though. We also will want to see logs for what is happening on the server side. Unfortunately, though, you won't be able to SSH in to the instance to get those logs. Instead, we'll have to change the CLI so that the instance is set up to export logs from the SSH server to StackDriver. I've added [this issue](https://github.com/googledatalab/datalab/issues/2027) to track that.

**Comment by ojarjur** [comment] 2018-08-23 22:08
This is almost certainly caused by #2014. I am putting together a fix for it right now and further updates will be in that issue.

**Closed by ojarjur** 2018-08-23 22:08 UTC
