### ISSUE TITLE
Window's "datalab create" causes the Putty client to baulk at "-o LogLevel=error"

### ISSUE THREAD

**Issue by jayprich** [googledatalab/datalab#1359] opened 2017-05-05 21:50 UTC
Command: datalab connect --verbosity debug --max-reconnects 0 tat-dl
Symptom: the Putty Windows app throws up a dialog complaining "-o" is an unrecognised argument
Excerpt from trace:
DEBUG: Executing command: ['C:\\Users\\tatli\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin\\sdk\\putty.exe', '-t', '-i', 'C:\\Users\\tatli\\.ssh\\google_compute_engine.ppk', u'-4', u'-o', u'LogLevel=error', u'-N', u'-L', u'localhost:8081:localhost:8080', u'datalab@104.155.126.40']
DEBUG: (gcloud.compute.ssh) [C:\Users\tatli\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\sdk\putty.exe] exited with return code [1].

Note that omitting "-o LogLevel=error" successfully opens an SSH tunnel

**Comment by chmeyers** [comment] 2017-05-05 21:52
This is a duplicate of https://github.com/googledatalab/datalab/issues/1356

A fix will be out in the next gcloud update but until then the known work-arounds for this issue are:
Downgrade to version 153.0.0 of the Cloud SDK, or
Use the Cloud Shell to run datalab connect

**Closed by chmeyers** 2017-05-05 21:52 UTC
