### ISSUE TITLE
Datalab offers optional upgrade to 1.2.20180713 which does not exist in GitHub releases

### ISSUE THREAD

**Issue by chc8** [googledatalab/datalab#2044] opened 2018-07-16 20:26 UTC
Datalab was very slow to start today. I was presented with the option to update datalab to version 1.2.20180713. The "what's new" link beside the message was for Github datalab releases. The datalab release page does not have a release for version 1.2.20180713. 

Is 1.2.20180713 a legitimate datalab update?

I also posted this question on StackOverflow.  Since the issue seems like it might be related to GitHub I am also posting it here.

[question asked on StackOverflow](https://stackoverflow.com/questions/51369513/datalab-offers-optional-upgrade-to-1-2-20180713-which-does-not-exist-on-github)

**Comment by yebrahim** [comment] 2018-07-16 20:32
Yes this is the latest release, I just created the [release tag](https://github.com/googledatalab/datalab/releases/tag/1.2.20180713).

What sort of slowness are you experiencing? Can you add more details?

**Comment by chc8** [comment] 2018-07-16 20:46
A few people on my team today opened datalab this morning with issues.  

For myself I noticed:
- At first datalab loaded to a blank page (still a datalab page, but no directory).  A browser refresh loaded the directory and menu.
- The datalab page in the browser was taking many minutes to load (browser showing busy).  The menu/file/folder icons were missing, but there were text descriptions instead.  After waiting for datalab to load the icons appeared.
- After restarting my datalab VM the slow loading behavior continued.
- The message offering an upgrade to 1.2.20180713 was new since the last time I used datalab.

**Comment by yebrahim** [comment] 2018-07-16 21:12
Interesting. I've just tested the new release again and it works fine for me, the difference between my setup and yours probably being due to your updating your instance, while I created a new one. Can you try a new instance and add your findings here?

Also, do you by any chance remember which version of Datalab you had before the update?

**Comment by chc8** [comment] 2018-07-16 21:23
I have not updated yet.  Currently I am on version 1.2.20180511.  I see the message offering an optional update to 1.2.20180713.  

I performed a "reset" on my datalab VM and the same issues occurred with a blank datalab page at first. 
 After changing the URL to point at the /datalab directory (from a deeper directory), and refreshing the browser, then the datalab page correctly loaded.

**Comment by yebrahim** [comment] 2018-07-16 21:33
Is that reproducible? Does the /datalab directory always load quickly compared to a deeper path? And does the slowness continue long after resetting the VM or is it just for a while then goes away?

Also related: I wonder if you have a big tree of files, it could be that our [file indexing](https://github.com/googledatalab/datalab/pull/1865) is slowing down the instance on startup. We haven't seen reports of this happening before though.

**Comment by chc8** [comment] 2018-07-16 21:44
It seems to be Intermittently reproducible while randomly browsing inside of datalab directories.  

I have not experienced this problem previously to today.

I would be glad to give you more information.  I also could just try upgrading to 1.2.20180713.

**Comment by chc8** [comment] 2018-07-17 18:34
The issue has gone away without any action taken on my behalf.  The worse offender today was 3.94s, and that only happened once out of roughly 20 attempts to reproduce the issue.  Yesterday it was minutes of waiting.

![timing 2018-07-17_12-30-20](https://user-images.githubusercontent.com/37651670/42838267-8f6c262a-89bd-11e8-9d8c-f34eeb0bd827.png)

**Comment by yebrahim** [comment] 2018-07-17 18:39
My suspicion was that it's a dependency that we load from a CDN that just had a bad day. The screenshot here just seems like a random network issue if it's rare and only takes a couple more seconds than usual.

If this happens again, please try to capture the offending resource and feel free to create a new issue. I'll close this one for now.

**Closed by yebrahim** 2018-07-17 18:39 UTC
