### ISSUE TITLE
Feature request: User authentication

### ISSUE THREAD

**Issue by dsignr** [googledatalab/datalab#907] opened 2016-07-11 03:41 UTC
Hi guys,
I know that Datalab restricts users to the current organization, but I was wondering if one could achieve multi-user support, something like Jupyter Hub?

Thank you :)

**Comment by chmeyers** [comment] 2017-03-10 20:01
Duplicate of https://github.com/googledatalab/datalab/issues/643

**Closed by chmeyers** 2017-03-10 20:01 UTC
