### ISSUE TITLE
It's not stable ?

### ISSUE THREAD

**Issue by WeilanCC** [googledatalab/datalab#2049] opened 2018-07-26 11:25 UTC
Hi, 

I have used product Datalab for about one month in the company. There exists always a problem, that appears surprisingly.

Here are some features:
(1) It appears when lanching the Datalab with Google cloud console.
(2) mainly several types of errors displayed: 
i. looping the error: [/usr/bin/ssh] exited with return code [255]
ii. Hanging up in the process:  Waiting for Datalab to be reachable at http://localhost:8081/
iii. With first error, sometimes it comes with the error: Permission denied (publickey)
(3) I have tried to solved these problem. BUT ! The surprising thing is that the problems appear randomly. So it's hard do trouble shooting. Why ? Because:  sometime, I stop the instance and restart it, then it works or I need to restart it several times; sometimes, I delete the Metadata and SSH keys in the Metadata tab and restart the instance, then it works, or I need to stop the instance firstly and then delete the Metadata and SSH keys to restart the instances; 
(4) One more feature when I can't start Datalab: sometimes I can use SSH via browser window but sometimes not
(5) So how can it be appears? here are some situations that I met: 
i. I stop my datalab and instance to have a break, for example, havaing lunch. After one hour, I can't restart my datalab. (What happened today T.T)
ii. I stop my instance to change my type of CPU or GPU and then I can't start my Datalab.
iii. I can't never start a second datalab.
(6) In a word, it's not stable. 

I don't know exactly if this is the problem of our side (firewall of company, internet connection, pc etc) or of the side GCP. Please mind my unknowing.

One more small defect: In the browser Micorsoft Edge, Ctrl-V will refresh the page.

**Comment by ojarjur** [comment] 2018-08-23 22:05
You are probably encountering the same issue as #2014.

We just today finally tracked down the root cause of that, so we are now working on getting out a fix.

**Comment by ojarjur** [comment] 2018-08-23 22:06
I'm going to close this specific issue; you can follow along for updates at #2014

**Closed by ojarjur** 2018-08-23 22:06 UTC
