### ISSUE TITLE
SSH connectivity failing when trying to re-connect to Datalab

### ISSUE THREAD

**Issue by kvassilakakis** [googledatalab/datalab#1361] opened 2017-05-08 16:25 UTC
More specifically, we cannot log-on to a Datalab after the first time that we set it up. In other words, we can create a Datalab, log-on to it for one time, and then once we disconnect, we cannot log-on back to it again. 

We have tried this in different projects, different locations of VM and we still get the same experience. The error it gives is the following:

```
This will create an SSH tunnel and may prompt you to create an rsa key pair.
Waiting for Datalab to be reachable at http://localhost:8081/
ssh: connect to host 35.184.17.194 port 22: Connection timed out
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
```

And the more you wait, the more of the same errors you receive.

With that in mind, have you or anyone in your team experienced something similar? 

As you can imagine, every time we want to test a model and we make some changes, if we disconnect, then we lose all the work, so we would really appreciate your help. And not to forget, this issue didn't use to happen before.

Thanks for the help!

**Comment by chmeyers** [comment] 2017-05-08 17:00
Omar, any ideas on what we might need to diagnose this?

**Comment by ojarjur** [comment] 2017-05-08 17:14
Sorry that you are hitting this, kvassilakakis. That clearly is not the sort of experience we aim to achieve.

I haven't seen this particular issue, but here are some options we have for debugging:

1. Try SSH'ing into the VM using the SSH button in the cloud console. That will let us know if the instance is actually reachable, or if it has some underlying issue with it.
2. Try running the underlying `gcloud compute ssh` command to see if it also fails. This will be something like `gcloud compute ssh --zone=<YOUR_ZONE> datalab@<YOUR_INSTANCE>`. This step will let us know if the issue is with gcloud SSH'ing into the VM, or with the way the `datalab` command line tool constructs the gcloud command.
3. If both of the above steps work, then add additional flags to the connect command to get additional information. Specifically, we have the `--verbosity=debug` and `--ssh-log-level=debug` flags that can be passed to the `datalab connect` command and will cause (a lot of) additional debugging information to be printed.

Please let us know what you find so that we can dig in further.

**Comment by kvassilakakis** [comment] 2017-05-08 19:15
Thank @ojarjur for the prompt reply.

Tried the first two steps. First works well, but the second doesn't. More specifically, I am getting the following error:

```
gcloud compute ssh --zone=us-central1-c datalab@kvnewdatlab
ssh: connect to host 104.198.165.43 port 22: Connection timed out
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255]
```
As you said, there is probably an issue with gcloud SSH'ing into the VM. Any thoughts how I can resolve that?

Thanks!

**Comment by ojarjur** [comment] 2017-05-08 19:25
@kvassilakakis 

Given what we know so far, the most likely cause of that is a firewall issue blocking the SSH connection.

This could be caused by the GCP firewall not allowing inbound SSH connections to your instance, or by a firewall on your machine not allowing outbound SSH connections.

To test the first case, look at the firewall rules for your project (in the Cloud Console), and make sure there is one that allows `tcp:22` traffic to the `datalab-network` network. Such a rule is created automatically by the `datalab create` command, but if your network admins run any sort of automated firewall-rule management tool on the project, it might be removing that rule.

To test the second case, try running the `gcloud compute ssh` command from within Cloud Shell (it is part of the Cloud Console). If that works, then the issue is probably some sort of firewall that your computer is sitting behind.

**Comment by kvassilakakis** [comment] 2017-05-09 15:34
@ojarjur 

Checked both. The first, it seems that `datalab-network` allows `tcp:22` traffic for many IP ranges, but it seems that the one that my new datalab VMs are connected to are not in those ranges.

In addition, I checked the following on the Cloud Shell, where I received a "Connection timeout" error.

```
gcloud compute ssh --quiet \
  --zone "[YOURZONE]" \
  --ssh-flag="-N" \
  --ssh-flag="-L" \
  --ssh-flag="localhost:8081:localhost:8080" \
  "${USER}@[YOURINSTANCENAME]"

ssh: connect to host 104.198.177.22 port 22: Connection timed out
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

Based on the above, what do you think I can change?

**Comment by kazunori279** [comment] 2017-05-15 08:55
just FYI,  I had the same issue. "gcloud compute ssh" didn't work while the "SSH" button on the console works. 

For my case I found so many old firewall rules and VPCs with "datalab-xxx" names. I suppose these have been created with older Datalab versions. I've deleted them all, created datalab instance again and it worked.

**Comment by kazunori279** [comment] 2017-05-21 19:41
I'm still seeing this issue every time I try to connect my Datalab instance. I always add a new firewall rule for allowing access to datalab-network from my IP address, but somehow the rules are removed automatically and overridden by the attached rules with hundreds of IP adresses... what's happening here?

https://www.dropbox.com/s/kixd8rsjghbc29x/Screen%20Shot%202017-05-22%20at%204.35.58%20AM.png?dl=0

**Comment by ojarjur** [comment] 2017-05-22 17:01
To close this out, I talked with kvassilakakis separately, and we confirmed that the issue was due to the project firewall rules and unrelated to the actual `datalab` tool.

**Closed by ojarjur** 2017-05-22 17:01 UTC
Labels: question

**Comment by bianbian2010** [comment] 2017-11-21 16:00
Hi @ojarjur I ran into the exact same issue..  `tcp: 22` is allowed in the firewall rules and the `gcloud compute ssh` works, however `datalab connect` would not work.

I understand this is an issue due to project firewall rules. Can you please advise on how to solve this? Thank you!

**Comment by ojarjur** [comment] 2017-11-21 18:29
@bianbian2010 If `gcloud compute ssh` works, then it's not an issue with the  firewall rules. In your particular case, the most likely cause is the Datalab server dying for some reason (e.g. running out of temp space, running out of memory, etc).

You have two options:

1. If you do not care about debugging the root cause, and just want to get back up and running, then try restarting the instance and then try to run `datalab connect ...` again.

2. If you want to dig into finding the root cause of what happened, then use `gcloud compute ssh` to SSH in to the VM, and then you can run `sudo docker ps -a` to find the ID of the Datalab container and then use `sudo docker logs ${CONTAINER_ID}` to see the logs for that container. You can also look in the Stack Driver logs for your VM (in the Cloud Console) and see if there are any log messages reporting an issue.

**Comment by vpatov** [comment] 2018-01-26 23:33
Hi, I have a similar issue. I can create Datalab instances, but I cannot use `datalab connect` to connect to them. However, I can use `gcloud compute ssh` to connect successfully. If I run `sudo docker ps -a ` on the datalab instance however, I cannot see the datalab container! The instance was created using the following command:

datalab create \
	--image-name ubuntu-1604-xenial-v20180122 \
	--no-connect \
	--disk-size-gb 150 \
	--idle-timeout 60m \
	--machine-type n1-standard-1 \
	--no-create-repository \
	--log-level debug \
	--max-reconnects 3 \
	--project my_project_name \
	my_instance_name

Any tips as to why the datalab docker container wouldn't exist?

**Comment by ojarjur** [comment] 2018-01-26 23:56
@vpatov "ubuntu-1604-xenial-v20180122" is not a Datalab Docker image.

The `--image-name` flag is for specifying the name of a custom Docker image if you have extended the standard Datalab Docker image (gcr.io/cloud-datalab/datalab).

If you are just wanting to use Datalab without custom modifications (e.g. additional packages installed), then you do not need to specify any value for the `--image-name` flag.

**Comment by vpatov** [comment] 2018-01-27 00:09
Thank you very much for that swift reply, I appreciate it, and that makes a lot of sense. That explains a problem I was facing earlier...

Unfortunately, (even with a new instance without the --image-name flag) my problem of not being able to use `datalab connect` persists, despite being able to successfully `gcloud compute ssh`.

Here's what I've done:
```$ datalab create test-datalab
# creates instance, but fails to connect
$ datalab connect test-datalab
Connecting to test-datalab.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
# this goes on and on, trying endlessly.
`
I've tried connecting with --port 8081 as well, with no success.

I can successfully ssh into the instance though. If I ssh in, and run `sudo docker ps`, I get this output:
```
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                      NAMES
008853754a4f        gcr.io/google_containers/fluentd-gcp:1.18   "/bin/sh -c '/usr/..."   32 minutes ago      Up 32 minutes                                  logger
f685e6efdaf1        gcr.io/cloud-datalab/datalab:latest         "/datalab/run.sh"        32 minutes ago      Up 32 minutes       127.0.0.1:8080->8080/tcp   datalab
```

So apparently the datalab container is exposing port 8080. However, the output of 
`netstat -at | grep 8080` comes up empty. 

Why is netstat not showing the port?
Could this be why `datalab connect test-datalab` is failing?

**Comment by ojarjur** [comment] 2018-01-27 00:36
@vpatov I am not familiar with netstat, so I cannot speak to why it produces the output that it does.

As for validating that Datalab is running inside of the VM, you should be able to run (from inside the VM) `curl localhost:8080/_info` and it will return a response from the Datalab server with details of the server.

Assuming that works, the most likely issue would be a port conflict (i.e. something else already using port 8081 on your local machine). To test that, try passing different arguments to the `--port` flag (e.g. `--port=8082`, `--port=8083`, ...)

If that does not work, then try the same command from inside of Cloud Shell; that will at least help us narrow down the source of the issue.

**Comment by vpatov** [comment] 2018-01-27 01:01
@ojarjur Datalab is indeed running from inside of the VM, I have confirmed as you have suggested. Something much more simple is failing too:
`gcloud compute ssh datalab@test-datalab`

I can ssh into other accounts just fine, but not the datalab account. 

Ports 8080-8083 are not in use by my local machine, so that's not the issue. 

I tried `gcloud compute ssh datalab@test-datalab` from both my local machine and from the google cloud shell, both have the same error:
```
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

However, I have checked the `authorized_keys` file in the /home/datalab/.ssh/ directory, and my `google_compute_engine.pub` key is present in the file.

**Comment by ojarjur** [comment] 2018-01-27 01:15
@vpatov That is very surprising.

Can you SSH in as a different account, run `ls -al /home/datalab` and look at what the permissions are currently set to for those files?

Additionally, have you enabled os-login on your project? If so, you may have to disable it on your Datalab instances.

**Comment by ojarjur** [comment] 2018-01-27 01:31
@vpatov It looks like os-login interferes with Datalab connections (tracking issue filed [here](https://github.com/googledatalab/datalab/issues/1929)).

Until we get that fixed, try adding a "enable-oslogin" metadata entry to your Datalab instance with a value of "FALSE".

**Comment by vpatov** [comment] 2018-01-27 01:45
OS Login had indeed been set to FALSE this whole time, I saw those notices as well.

I have found the source of my issue. It was quite bizzarre. My computer's hostname/name had a space in it (something like `user1232123123@myname's Macbook`). I noticed in different places in Google's Cloud documentation, it stated that the SSH keys must have a specific format of `ssh-rsa keyblob name`. I thought that since I was able to ssh successfully into everything that this wasn't an issue. Eventually I tried to remedy it by manually changing the name in my respective public key as well as in the `authorized_keys` files on the instance. However, I guess those SSH keys are also present in the project metadata, and tied to my account, and command-line usage of `gcloud` is tied with my account, thus my manual edits were not registered (or something). 

I changed my computer's hostname and name to something without spaces, restarted the comp, deleted all my google ssh files (keys and hosts), used `gcloud compute config-ssh` to create a new key, created a new datalab instance, and was able to successfully connect to it. :)

I must have spent a total of 20 hours dealing with this. Don't put spaces in names kids...

**Comment by ojarjur** [comment] 2018-01-27 02:04
@vpatov I'm sorry you hit that, but I'm glad you were able to work it out.

That really sounds like it should be filed as a bug against the Cloud SDK; I think they should be somehow sanitizing hostnames before incorporating them into the SSH keys metadata.

I've filed an issue [here](https://b.corp.google.com/issues/72572352). Can you add any additional information you have and/or correct anything in it that I got wrong?

Thanks for following up with this.

**Comment by vpatov** [comment] 2018-01-28 02:27
@ojarjur I can't seem to get to that link, it leads me to a sign-in page for SSO/ moma. I tried registering myself but that's not working right now...

**Comment by vpatov** [comment] 2018-01-28 03:43
@ojarjur The issue looks good, thanks for following through. Hostnames should definitely be sanitized. Also, my organization shouldn't put spaces in our hostnames.. :)

**Comment by zankbennett** [comment] 2018-02-07 23:15
Hi @ojarjur I have the same problem you closed on May 21, 2017. Would you please provide some details on how to view my project firewall rules and solve this issue?
I cannot access my VM after I performed the following:

`datalab delete --keep-disk datalab-zank`
`datalab create datalab-zank`

Since then (this morning), I cannot connect and see the Error below. Again, I  have all the same symptoms mentioned up to your May 21 post.
Thanks!!

```
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

**Comment by ojarjur** [comment] 2018-02-07 23:29
@zankbennett The symptoms you describe can be caused by a lot of different issues, so it need not be the same root cause as this issue.

The steps you should take to debug are:

1. Run `gcloud compute firewall-rules list --filter "network=datalab-network"` and confirm that there is one (and *only* one) firewall rule for that network. That rule should have an `ALLOW` field of `tcp:22`. That will tell you whether or not your firewall rule is set up correctly.
2. Connect to the instance using the "SSH" button in the Cloud Console. That will tell you whether or not the instance itself is having issues.

**Comment by zankbennett** [comment] 2018-02-07 23:46
Thanks @ojarjur 
I have three rules:

```
NAME                         NETWORK          DIRECTION  PRIORITY  ALLOW    DENY
datalab-network-allow-http   datalab-network  INGRESS    1000      tcp:80
datalab-network-allow-https  datalab-network  INGRESS    1000      tcp:443
datalab-network-allow-ssh    datalab-network  INGRESS    1000      tcp:22
```

Do I need to remove the first two?
I have the Firewalls unchecked in the instance.
![image](https://user-images.githubusercontent.com/6068362/35947699-0846d1d0-0c1e-11e8-8edb-d5fd3c8d5190.png)

**Comment by ojarjur** [comment] 2018-02-07 23:50
@zankbennett Those firewall rules won't cause issues, but I would recommend removing the first two, as they leave your instance more open than we recommend.

Can you connect to the instance using the SSH button in the Cloud Console?

**Comment by zankbennett** [comment] 2018-02-07 23:55
@ojarjur 
OK. I don't know how to remove those.
And yes, I can connect using the SSH button. I have all the same symptoms as the person you helped up to May 22, 2017.

Any ideas what I can do next?
Thanks!

**Comment by ojarjur** [comment] 2018-02-08 00:01
@zankbennett The original issue was caused by the firewall rules being wrong, so what you are seeing is being caused by something different.

If you are *not* using Cloud Shell, then try running `datalab connect ...` from inside of Cloud Shell.

Alternatively, if you *are* using Cloud Shell, then try running `datalab connect ...` from outside of Cloud Shell.

That will tell you if it is the client machine (where you run `datalab connect`) that is having issues.

**Comment by zankbennett** [comment] 2018-02-08 00:07
Thanks, @ojarjur 
I _am_ using Cloud Shell. How do I try running `datalab connect ...` from outside of Cloud Shell?
Can I do that from the SSH window I opened? If so, could you please give me the command?
Thanks!

**Comment by ojarjur** [comment] 2018-02-08 00:11
@zankbennett The way you would do it outside of Cloud Shell is to install the Cloud SDK and the `datalab` component on your machine, and then run it there.

Instructions for doing that are in [the Quickstart page](https://cloud.google.com/datalab/docs/quickstart).

**Comment by zankbennett** [comment] 2018-02-08 00:19
@ojarjur 
Great. I did that, and now I get:
`A nested call to gcloud failed.`
When running `datalab connect ...`

Any ideas what this means? I really appreciate your help.

**Comment by ojarjur** [comment] 2018-02-08 00:22
@zankbennett There should be an error message printed before `A nested call to gcloud failed`.

I.E. that message is referring to the output that came right before it, and explaining that it was being reported by `gcloud`.

**Comment by zankbennett** [comment] 2018-02-08 00:25
Hi @ojarjur 
![image](https://user-images.githubusercontent.com/6068362/35948835-6737b1be-0c23-11e8-95d0-24588cc19f1a.png)
That's all I see

**Comment by ojarjur** [comment] 2018-02-08 00:27
@zankbennett That is unexpected.

Try running it with the flag `--verbosity=debug`. That will tell you more information about what it is doing.

**Comment by zankbennett** [comment] 2018-02-08 00:30
@ojarjur 
![image](https://user-images.githubusercontent.com/6068362/35948976-136745ee-0c24-11e8-9b26-87a4ed9c942d.png)
Hmm.

Do you have the ability to G-chat with me?
zankbennett@gmail.com

**Comment by ojarjur** [comment] 2018-02-08 00:32
@zankbennett Let's try something else:

Run the command `gcloud compute ssh datalab-zank` and see if you can connect to your instance just using gcloud.

Go ahead and try this from both Cloud Shell and your local machine.

**Comment by zankbennett** [comment] 2018-02-08 00:50
@ojarjur 
Thanks. I needed to set the correct project. Now I'm getting this error.

```
^CTCHQMBAkBennett:~ zank2$ datalab connect datalab-zank
Connecting to datalab-zank.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
datalab@35.203.191.11: Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
datalab@35.203.191.11: Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
```

**Comment by ojarjur** [comment] 2018-02-08 01:01
@zankbennett Do you have "os-login" enabled in your project? If so, that is not supported by Datalab yet.

**Comment by zankbennett** [comment] 2018-02-08 01:13
@ojarjur 
How would I know if I have "os-login" enabled in your project?

Everything worked fine for months. Then I updated datalab by the commands above and now I cannot connect. I didn't make any other changes, so I don't think it's a project-wide issue. Others on my team are also able to connect (they have not updated).

**Comment by ojarjur** [comment] 2018-02-08 01:16
@zankbennett Try running `gcloud compute ssh datalab-zank` and see if it works or fails.

If it fails, then there may be an upstream issue in the latest version of gcloud.

Also, run `gcloud version` and let me know which version of the tool you are using.

**Comment by zankbennett** [comment] 2018-02-08 01:23
@ojarjur 
`gcloud compute ssh datalab-zank` works (same as the user above whose symptoms are identical to mine up to the point where you closed this issue)

`gcloud version` gives:

```
Google Cloud SDK 185.0.0
alpha 2017.09.15
app-engine-python 1.9.65
beta 2017.09.15
bq 2.0.28
core 2018.01.12
datalab 20180105
gcloud
gsutil 4.28
```

**Comment by ojarjur** [comment] 2018-02-08 01:29
@zankbennett That version of Datalab has a known issue https://github.com/googledatalab/datalab/issues/1898, so you should upgrade when you can (and until then, restart any instances you create to work around that issue).

However, that issue doesn't cause SSH issues.

What do you get if you run `gcloud compute ssh datalab@datalab-zank`? That is what the `datalab` command does under the hood (i.e. it SSH's as the user `datalab` instead of as you).

**Comment by noahgift** [comment] 2018-02-08 03:17
Hi, I also can verify hostname with space is a repeatable bug.  Just spent 2 hours on this until I found this thread.

**Comment by zankbennett** [comment] 2018-02-08 14:53
Good morning, @ojarjur 
When running 
`gcloud compute ssh datalab@datalab-zank`

I get:
`ERROR: (gcloud.compute.ssh) Instance [datalab-zank] in zone [us-west1-a] has not been allocated an external IP address yet. Try rerunning this command later.`

I'll update Datalab momentarily

**Comment by zankbennett** [comment] 2018-02-08 17:36
@ojarjur 
I've updated `gcloud` to 188. Then I ran
`datalab delete --keep-disk datalab-zank`
Followed by
`datalab create datalab-zank --zone us-west1-a`

I received this notice:
`The network `datalab-network` has firewall rules that were not created by the `datalab` command line tool. Instances created in that network may be open to traffic that they should not be exposed to.`

Then after responding `y` to:
`Do you still want to use this network? (y/[n]): `

I get the same error:
```
Waiting for Datalab to be reachable at http://localhost:8081/
ssh: connect to host 35.185.236.27 port 22: Connection refused
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
```

Any ideas?

**Comment by ojarjur** [comment] 2018-02-08 18:26
@zankbennett The error message you got in response to `gcloud compute ssh datalab@datalab-zank` was because your instance wasn't running (it automatically shuts itself off when not being used for an extended period).

Make sure it is running, and then try that again.

**Comment by zankbennett** [comment] 2018-02-08 20:16
@ojarjur 
It works when the instance is running :)

Now (for _some_ reason) I can start datalab and view Jupyter. Thanks @ojarjur 

I think the "fix" was
1. updating Gcloud (and Datalab) like this:
`gcloud components update`

2. Updating Datalab instance like this:
```
datalab delete --keep-disk [my_instance_name]
datalab create [my_instance_name] --zone [my_zone_name_same_as_what_I_deleted_above]
```
I can only guess that my issue arose when I initially created a datalab instance with an older version of gcloud and datalab.

Have a great day!

**Comment by ojarjur** [comment] 2018-02-08 20:25
@zankbennett I'm glad to know things are working for you now.

The symptoms you saw are really surprising. That version (20180105) has a known issue, but that issue is not known to cause connection problems.

**Comment by iethan** [comment] 2018-03-07 21:44
@zankbennett That issue happened to me and by updating the Cloudshell GCloud SDK and running a new instance, it worked. I did have a Dataproc cluster running that I stopped between the error and when it started working again. I doubt they are related though. 

Thanks @ojarjur for the responsiveness!

**Comment by luqon** [comment] 2018-04-23 09:30
Hey @ojarjur. I am having similar issues connecting to Datalab as described here, but none of the solutions presented seem to work for me. I have been using Datalab for quite a while without issues, but at some point roughly 2 months ago it stopped working. After using the `datalab connect [my_instance_name]` command and filling in my passphrase nothing would happen.

I can ssh into the instance without issues, although sometimes it will give me an infinite string of `Permission denied (publickey)` errors. Stopping and restarting the instance sometimes solves that, but not always. It seems kind of random. 

I have stopped the instance, deleted the instance (including the persistent disk) and have updated the GCloud SDK every time I am prompted to do so, removed my SSH keys and made new ones, but the problem persists. Nobody else within the same project seems to have the same issue.

If I use `datalab connect [my_instance_name] --ssh-log-level debug` I get the following:

`debug1: channel 1: free: direct-tcpip: listening port 8081 for localhost port 8080, connect from 127.0.0.1 port 52241 to 127.0.0.1 port 8081, nchannels 4
debug1: Connection to port 8081 forwarding to localhost port 8080 requested.
debug1: channel 1: new [direct-tcpip]
debug1: channel 2: free: direct-tcpip: listening port 8081 for localhost port 8080, connect from 
127.0.0.1 port 52243 to 127.0.0.1 port 8081, nchannels 4
debug1: Connection to port 8081 forwarding to localhost port 8080 requested.
debug1: channel 2: new [direct-tcpip]`

And so on without end. 

Using `docker ps -a` within the instance when this happens shows me that the Datalab docker keeps on being restarted every few seconds. Maybe this is what causes this behaviour but I have no clue how to stop it.

Any help on this would be greatly appreciated, cause I burned through many hours trying to fix this and I have no clue how to proceed.

**Comment by ojarjur** [comment] 2018-04-30 21:16
@luqon Please open a new issue with your reported details; no one will notice new comments on a closed issue.

When you open that new issue, also try SSH'ing in to your VM, using `docker ps -a` to get the list of failing containers, and then run `docker logs <CONTAINER_ID>` to get the logs from the most recent failing container.
