### ISSUE TITLE
Missing package causes error in sample: "Introduction to Python"

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#936] opened 2016-08-08 04:56 UTC
Need to add package or change sample (the latter may be easier for now)
%%bash
apt-get install -y -q libxslt-dev libxml2-dev
pip install -q scrapy

debconf: delaying package configuration, since apt-utils is not installed
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-OqPUd_/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NBepB4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-OqPUd_/cryptography/

**Comment by parthea** [comment] 2016-08-08 12:25
I was unable to reproduce this issue. Please could you post the output with the `-q` (quiet option) removed in order to get more insight into the root cause?

For example,
```
%%bash
apt-get install -y libxslt-dev libxml2-dev
pip install scrapy
```

```
>%%bash
>apt-get install -y -q libxslt-dev libxml2-dev
>pip install -q scrapy
Reading package lists...
Building dependency tree...
Reading state information...
libxml2-dev is already the newest version.
The following NEW packages will be installed:
  libxslt1-dev libxslt1.1
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 743 kB of archives.
After this operation, 2838 kB of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main libxslt1.1 amd64 1.1.28-2+deb8u1 [232 kB]
Get:2 http://security.debian.org/ jessie/updates/main libxslt1-dev amd64 1.1.28-2+deb8u1 [511 kB]
Fetched 743 kB in 0s (1177 kB/s)
Selecting previously unselected package libxslt1.1:amd64.
(Reading database ... 18099 files and directories currently installed.)
Preparing to unpack .../libxslt1.1_1.1.28-2+deb8u1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2+deb8u1) ...
Selecting previously unselected package libxslt1-dev:amd64.
Preparing to unpack .../libxslt1-dev_1.1.28-2+deb8u1_amd64.deb ...
Unpacking libxslt1-dev:amd64 (1.1.28-2+deb8u1) ...
Setting up libxslt1.1:amd64 (1.1.28-2+deb8u1) ...
Setting up libxslt1-dev:amd64 (1.1.28-2+deb8u1) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
```

**Comment by parthea** [comment] 2016-08-09 02:31
The following seems to work, but perhaps its not suitable for a notebook titled "Introduction to Python"
```
%%bash
apt-get install -y libxslt-dev libxml2-dev libffi-dev libssl-dev
pip install scrapy
!touch /usr/local/lib/python2.7/dist-packages/zope/__init__.py
```

```
> import scrapy
> scrapy.__version__
u'1.1.1'
```

**Comment by parthea** [comment] 2016-08-14 17:45
Fixed in https://github.com/googledatalab/notebooks/commit/5ef81a1a74b05e72aba44079ff4cc1c362f9a970

This issue can be closed.

**Closed** 2016-08-18 20:43 UTC
