### ISSUE TITLE
Rendering Date types in query results is one day behind

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/datalab#1195] opened 2017-02-17 23:33 UTC
In query results tables that contain Date types, the data shows always one day behind the actual values.

**Comment by chmeyers** [comment] 2017-03-10 19:20
Is this due to UTC/timezone conversion?

**Comment by yebrahim** [comment] 2017-03-10 19:47
Didn't dig deep enough for the cause, could be. We get the data correctly, but when rendered to the HTML table they should one day behind.

**Comment by jimmc** [comment] 2017-03-14 17:46
Code:
%%bq query
select DATETIME('2017-03-14 10:20:30')

Result:
f0_
Mar 14, 2017, 3:20:30 AM

Local time is PDT = UCT - 7, so it does look like a timezone issue, with the DATETIME parsing assuming UCT and the output assuming PDT.

**Comment by qimingj** [comment] 2017-03-14 17:53
Jim, I am actually working on this one since I have another similar bug assigned to me.

The problem is that Google Chart by default shows local time, and The DateTime from BQ is considered as UTC time by Python. One way to fix is to modify charting.ts to display UTC time instead of local time.

**Comment by jimmc** [comment] 2017-03-24 16:47
I have been working on this for a while. The solution agreed to by the people I have talked to is to make everything output absolute dates and times in UTC, with the timezone in the output. This requires detangling civil dates and times (such as BQ's DATE, TIME, and DATETIME datatypes) from absolute times (BQ's TIMESTAMP datatype), and ensuring that all output formats consistently use UTC (including BQ tables, pandas dataframes, and google charts).

**Comment by jimmc** [comment] 2017-03-28 23:59
Dataframes are converted to strings in the kernel, which uses UTC, but those strings don't include the timezone. To be consistent with that, and to avoid hacking the pandas library, I will use the same formats when converting strings in the client, which means no timezone. Everything is UTC.

**Closed** 2017-03-30 15:39 UTC
Labels: bug, P1
